import { createApp } from 'vue'
import App from './App.vue'
import { createPinia } from 'pinia'
import { createVuetify } from 'vuetify'
import { createI18n } from 'vue-i18n'
import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'

const messages = {
  en: {
    appTitle: 'Portfolio Rebalancing',
    investments: '💰 Investments',
    groups: '📊 Groups',
    total: 'Total',
    stockName: 'Stock Name',
    stockCode: 'Stock Code',
    shares: 'Shares',
    price: 'Price',
    value: 'Value ($)',
    add: 'Add',
    stock: 'Stock',
    actions: 'Actions',
    groupName: 'Group Name',
    target: 'Target',
    buy: 'Buy',
    sell: 'Sell',
    addStock: '+ Add Stock',
    deleteGroup: 'Delete Group',
    footer: '© {year} {company}',
    snapshots: '📸 Snapshots',
    snapshotName: 'Snapshot Name',
    save: 'Save',
    noSnapshots: 'No snapshots saved',
    confirmLoadSnapshot: 'Are you sure you want to load this snapshot? Current data will be overwritten.',
    confirmDeleteSnapshot: 'Are you sure you want to delete this snapshot?',
    snapshotGraph: 'Snapshot Value History',
    apiKeyLabel: 'Twelve Data API Key',
    apiKeyPlaceholder: 'Enter your API key'
  },
  zh: {
    appTitle: '投资组合再平衡',
    investments: '💰 投资',
    groups: '📊 组合',
    total: '总计',
    stockName: '股票名称',
    stockCode: '股票代码',
    shares: '股数',
    price: '价格',
    value: '价值 ($)',
    add: '添加',
    stock: '股票',
    actions: '操作',
    groupName: '组合名称',
    target: '目标',
    buy: '买入',
    sell: '卖出',
    addStock: '+ 添加股票',
    deleteGroup: '删除组合',
    footer: '© {year} {company}',
    snapshots: '📸 快照',
    snapshotName: '快照名称',
    save: '保存',
    noSnapshots: '没有保存的快照',
    confirmLoadSnapshot: '确定要加载此快照吗？当前数据将被覆盖。',
    confirmDeleteSnapshot: '确定要删除此快照吗？',
    snapshotGraph: '快照价值历史',
    apiKeyLabel: 'Twelve Data API 密钥',
    apiKeyPlaceholder: '输入您的 API 密钥'
  },
  es: {
    appTitle: 'Reequilibrio de Cartera',
    investments: '💰 Inversiones',
    groups: '📊 Grupos',
    total: 'Total',
    stockName: 'Nombre de Acción',
    stockCode: 'Código de Acción',
    shares: 'Acciones',
    price: 'Precio',
    value: 'Valor ($)',
    add: 'Añadir',
    stock: 'Acción',
    actions: 'Acciones',
    groupName: 'Nombre del Grupo',
    target: 'Objetivo',
    buy: 'Comprar',
    sell: 'Vender',
    addStock: '+ Añadir Acción',
    deleteGroup: 'Eliminar Grupo',
    footer: '© {year} {company}',
    snapshots: '📸 Instantáneas',
    snapshotName: 'Nombre de la instantánea',
    save: 'Guardar',
    noSnapshots: 'No hay instantáneas guardadas',
    confirmLoadSnapshot: '¿Estás seguro de que quieres cargar esta instantánea? Los datos actuales se sobrescribirán.',
    confirmDeleteSnapshot: '¿Estás seguro de que quieres eliminar esta instantánea?',
    snapshotGraph: 'Historial de valor de instantáneas',
    apiKeyLabel: 'Clave de API de Twelve Data',
    apiKeyPlaceholder: 'Ingrese su clave de API'
  },
  de: {
    appTitle: 'Portfolio-Rebalancing',
    investments: '💰 Investitionen',
    groups: '📊 Gruppen',
    total: 'Gesamt',
    stockName: 'Aktienname',
    stockCode: 'Aktienkürzel',
    shares: 'Anteile',
    price: 'Preis',
    value: 'Wert ($)',
    add: 'Hinzufügen',
    stock: 'Aktie',
    actions: 'Aktionen',
    groupName: 'Gruppenname',
    target: 'Ziel',
    buy: 'Kaufen',
    sell: 'Verkaufen',
    addStock: '+ Aktie hinzufügen',
    deleteGroup: 'Gruppe löschen',
    footer: '© {year} {company}',
    snapshots: '📸 Schnappschüsse',
    snapshotName: 'Schnappschuss-Name',
    save: 'Speichern',
    noSnapshots: 'Keine Schnappschüsse gespeichert',
    confirmLoadSnapshot: 'Sind Sie sicher, dass Sie diesen Schnappschuss laden möchten? Aktuelle Daten werden überschrieben.',
    confirmDeleteSnapshot: 'Sind Sie sicher, dass Sie diesen Schnappschuss löschen möchten?',
    snapshotGraph: 'Snapshot-Wertverlauf',
    apiKeyLabel: 'Twelve Data API-Schlüssel',
    apiKeyPlaceholder: 'Geben Sie Ihren API-Schlüssel ein'
  },
  ja: {
    appTitle: 'ポートフォリオ・リバランス',
    investments: '💰 投資',
    groups: '📊 グループ',
    total: '合計',
    stockName: '銘柄名',
    stockCode: '銘柄コード',
    shares: '株数',
    price: '価格',
    value: '評価額 ($)',
    add: '追加',
    stock: '銘柄',
    actions: '操作',
    groupName: 'グループ名',
    target: '目標',
    buy: '買い',
    sell: '売り',
    addStock: '+ 銘柄を追加',
    deleteGroup: 'グループを削除',
    footer: '© {year} {company}',
    snapshots: '📸 スナップショット',
    snapshotName: 'スナップショット名',
    save: '保存',
    noSnapshots: '保存されたスナップショットはありません',
    confirmLoadSnapshot: 'このスナップショットを読み込みますか？現在のデータは上書きされます。',
    confirmDeleteSnapshot: 'このスナップショットを削除してもよろしいですか？',
    snapshotGraph: 'スナップショット価値履歴',
    apiKeyLabel: 'Twelve Data API キー',
    apiKeyPlaceholder: 'API キーを入力してください'
  },
  ko: {
    appTitle: '포트폴리오 리밸런싱',
    investments: '💰 투자',
    groups: '📊 그룹',
    total: '합계',
    stockName: '종목명',
    stockCode: '종목 코드',
    shares: '주식 수',
    price: '가격',
    value: '가치 ($)',
    add: '추가',
    stock: '주식',
    actions: '작업',
    groupName: '그룹명',
    target: '목표',
    buy: '매수',
    sell: '매도',
    addStock: '+ 주식 추가',
    deleteGroup: '그룹 삭제',
    footer: '© {year} {company}',
    snapshots: '📸 스냅샷',
    snapshotName: '스냅샷 이름',
    save: '저장',
    noSnapshots: '저장된 스냅샷 없음',
    confirmLoadSnapshot: '이 스냅샷을 불러오시겠습니까? 현재 데이터가 덮어씌워집니다.',
    confirmDeleteSnapshot: '이 스냅샷을 삭제하시겠습니까?',
    snapshotGraph: '스냅샷 가치 기록',
    apiKeyLabel: 'Twelve Data API 키',
    apiKeyPlaceholder: 'API 키를 입력하세요'
  }
}

const i18n = createI18n({
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  messages
})

const pinia = createPinia()
const vuetify = createVuetify()

createApp(App).use(pinia).use(vuetify).use(i18n).mount('#app')
